version: "3.1"

services:
  neo4j:
    container_name: "neo4j"
    image: "neo4j:4.4.5-community"
    restart: "on-failure"
    volumes:
      - "./neo4j/data:/data"
      - "./neo4j/plugins:/var/lib/neo4j/plugins"
      - "./neo4j/conf:/var/lib/neo4j/conf"
    ports:
      - "7474:7474"
      - "7687:7687"